### ISSUE TITLE
התוכנית לא רצה

### ISSUE THREAD

**Issue by themoshe12** [DorKremer/AirBNE#2]
if (list.Count == 0)
            {
                stream = File.Open("items.mdl", FileMode.Open);
                var binaryFormatter = new System.Runtime.Serialization.Formatters.Binary.BinaryFormatter();
                Rentable item;
                while (stream.Position < stream.Length)
                {
                    item = (Rentable)binaryFormatter.Deserialize(stream);
                    if (item.Occupied)
                        Order.item = item;
                    list.Add(item);
                }
            }
לא נותן לי לפתוח את התוכנה כי הוא לא מוצא את הקובץ במחשב נופל בשורה הראשונה של הסטרים

**Comment by DorKremer** [comment]
באגים בקוד שלנו? לא נשמע הגיוני
